/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace OracleUtils {
  export type ValidatedPriceStruct = {
    token: PromiseOrValue<string>;
    min: PromiseOrValue<BigNumberish>;
    max: PromiseOrValue<BigNumberish>;
    timestamp: PromiseOrValue<BigNumberish>;
    provider: PromiseOrValue<string>;
  };

  export type ValidatedPriceStructOutput = [
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    token: string;
    min: BigNumber;
    max: BigNumber;
    timestamp: BigNumber;
    provider: string;
  };
}

export interface PythPriceFeedProviderInterface extends utils.Interface {
  functions: {
    "decimals()": FunctionFragment;
    "getOraclePrice(address,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "priceFeedIds(address)": FunctionFragment;
    "pyth()": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "setPriceFeedId(address,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "decimals"
      | "getOraclePrice"
      | "owner"
      | "priceFeedIds"
      | "pyth"
      | "setOwner"
      | "setPriceFeedId"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getOraclePrice",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceFeedIds",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "pyth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceFeedId",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOraclePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceFeedIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pyth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPriceFeedId",
    data: BytesLike
  ): Result;

  events: {
    "Pyth_OwnerSet(address)": EventFragment;
    "Pyth_PriceFeedIdSet(address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Pyth_OwnerSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Pyth_PriceFeedIdSet"): EventFragment;
}

export interface Pyth_OwnerSetEventObject {
  newOwner: string;
}
export type Pyth_OwnerSetEvent = TypedEvent<[string], Pyth_OwnerSetEventObject>;

export type Pyth_OwnerSetEventFilter = TypedEventFilter<Pyth_OwnerSetEvent>;

export interface Pyth_PriceFeedIdSetEventObject {
  token: string;
  priceFeedId: string;
}
export type Pyth_PriceFeedIdSetEvent = TypedEvent<
  [string, string],
  Pyth_PriceFeedIdSetEventObject
>;

export type Pyth_PriceFeedIdSetEventFilter =
  TypedEventFilter<Pyth_PriceFeedIdSetEvent>;

export interface PythPriceFeedProvider extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PythPriceFeedProviderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    decimals(overrides?: CallOverrides): Promise<[number]>;

    getOraclePrice(
      token: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[OracleUtils.ValidatedPriceStructOutput]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    priceFeedIds(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    pyth(overrides?: CallOverrides): Promise<[string]>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPriceFeedId(
      token: PromiseOrValue<string>,
      priceFeedId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  decimals(overrides?: CallOverrides): Promise<number>;

  getOraclePrice(
    token: PromiseOrValue<string>,
    arg1: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<OracleUtils.ValidatedPriceStructOutput>;

  owner(overrides?: CallOverrides): Promise<string>;

  priceFeedIds(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  pyth(overrides?: CallOverrides): Promise<string>;

  setOwner(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPriceFeedId(
    token: PromiseOrValue<string>,
    priceFeedId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    decimals(overrides?: CallOverrides): Promise<number>;

    getOraclePrice(
      token: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<OracleUtils.ValidatedPriceStructOutput>;

    owner(overrides?: CallOverrides): Promise<string>;

    priceFeedIds(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    pyth(overrides?: CallOverrides): Promise<string>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPriceFeedId(
      token: PromiseOrValue<string>,
      priceFeedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Pyth_OwnerSet(address)"(newOwner?: null): Pyth_OwnerSetEventFilter;
    Pyth_OwnerSet(newOwner?: null): Pyth_OwnerSetEventFilter;

    "Pyth_PriceFeedIdSet(address,bytes32)"(
      token?: null,
      priceFeedId?: null
    ): Pyth_PriceFeedIdSetEventFilter;
    Pyth_PriceFeedIdSet(
      token?: null,
      priceFeedId?: null
    ): Pyth_PriceFeedIdSetEventFilter;
  };

  estimateGas: {
    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    getOraclePrice(
      token: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    priceFeedIds(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pyth(overrides?: CallOverrides): Promise<BigNumber>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPriceFeedId(
      token: PromiseOrValue<string>,
      priceFeedId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOraclePrice(
      token: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceFeedIds(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pyth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPriceFeedId(
      token: PromiseOrValue<string>,
      priceFeedId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
