/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace PythStructs {
  export type PriceStruct = {
    price: PromiseOrValue<BigNumberish>;
    conf: PromiseOrValue<BigNumberish>;
    expo: PromiseOrValue<BigNumberish>;
    publishTime: PromiseOrValue<BigNumberish>;
  };

  export type PriceStructOutput = [BigNumber, BigNumber, number, BigNumber] & {
    price: BigNumber;
    conf: BigNumber;
    expo: number;
    publishTime: BigNumber;
  };

  export type PriceFeedStruct = {
    id: PromiseOrValue<BytesLike>;
    price: PythStructs.PriceStruct;
    emaPrice: PythStructs.PriceStruct;
  };

  export type PriceFeedStructOutput = [
    string,
    PythStructs.PriceStructOutput,
    PythStructs.PriceStructOutput
  ] & {
    id: string;
    price: PythStructs.PriceStructOutput;
    emaPrice: PythStructs.PriceStructOutput;
  };

  export type TwapPriceFeedStruct = {
    id: PromiseOrValue<BytesLike>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    twap: PythStructs.PriceStruct;
    downSlotsRatio: PromiseOrValue<BigNumberish>;
  };

  export type TwapPriceFeedStructOutput = [
    string,
    BigNumber,
    BigNumber,
    PythStructs.PriceStructOutput,
    number
  ] & {
    id: string;
    startTime: BigNumber;
    endTime: BigNumber;
    twap: PythStructs.PriceStructOutput;
    downSlotsRatio: number;
  };
}

export interface IPythInterface extends utils.Interface {
  functions: {
    "getEmaPriceNoOlderThan(bytes32,uint256)": FunctionFragment;
    "getEmaPriceUnsafe(bytes32)": FunctionFragment;
    "getPriceNoOlderThan(bytes32,uint256)": FunctionFragment;
    "getPriceUnsafe(bytes32)": FunctionFragment;
    "getTwapUpdateFee(bytes[])": FunctionFragment;
    "getUpdateFee(bytes[])": FunctionFragment;
    "parsePriceFeedUpdates(bytes[],bytes32[],uint64,uint64)": FunctionFragment;
    "parsePriceFeedUpdatesUnique(bytes[],bytes32[],uint64,uint64)": FunctionFragment;
    "parsePriceFeedUpdatesWithConfig(bytes[],bytes32[],uint64,uint64,bool,bool,bool)": FunctionFragment;
    "parseTwapPriceFeedUpdates(bytes[],bytes32[])": FunctionFragment;
    "updatePriceFeeds(bytes[])": FunctionFragment;
    "updatePriceFeedsIfNecessary(bytes[],bytes32[],uint64[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getEmaPriceNoOlderThan"
      | "getEmaPriceUnsafe"
      | "getPriceNoOlderThan"
      | "getPriceUnsafe"
      | "getTwapUpdateFee"
      | "getUpdateFee"
      | "parsePriceFeedUpdates"
      | "parsePriceFeedUpdatesUnique"
      | "parsePriceFeedUpdatesWithConfig"
      | "parseTwapPriceFeedUpdates"
      | "updatePriceFeeds"
      | "updatePriceFeedsIfNecessary"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getEmaPriceNoOlderThan",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmaPriceUnsafe",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceNoOlderThan",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceUnsafe",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTwapUpdateFee",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getUpdateFee",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "parsePriceFeedUpdates",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "parsePriceFeedUpdatesUnique",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "parsePriceFeedUpdatesWithConfig",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "parseTwapPriceFeedUpdates",
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePriceFeeds",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePriceFeedsIfNecessary",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEmaPriceNoOlderThan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmaPriceUnsafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceNoOlderThan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceUnsafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTwapUpdateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUpdateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parsePriceFeedUpdates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parsePriceFeedUpdatesUnique",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parsePriceFeedUpdatesWithConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parseTwapPriceFeedUpdates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePriceFeeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePriceFeedsIfNecessary",
    data: BytesLike
  ): Result;

  events: {
    "PriceFeedUpdate(bytes32,uint64,int64,uint64)": EventFragment;
    "TwapPriceFeedUpdate(bytes32,uint64,uint64,int64,uint64,uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PriceFeedUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TwapPriceFeedUpdate"): EventFragment;
}

export interface PriceFeedUpdateEventObject {
  id: string;
  publishTime: BigNumber;
  price: BigNumber;
  conf: BigNumber;
}
export type PriceFeedUpdateEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  PriceFeedUpdateEventObject
>;

export type PriceFeedUpdateEventFilter = TypedEventFilter<PriceFeedUpdateEvent>;

export interface TwapPriceFeedUpdateEventObject {
  id: string;
  startTime: BigNumber;
  endTime: BigNumber;
  twapPrice: BigNumber;
  twapConf: BigNumber;
  downSlotsRatio: number;
}
export type TwapPriceFeedUpdateEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, number],
  TwapPriceFeedUpdateEventObject
>;

export type TwapPriceFeedUpdateEventFilter =
  TypedEventFilter<TwapPriceFeedUpdateEvent>;

export interface IPyth extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPythInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getEmaPriceNoOlderThan(
      id: PromiseOrValue<BytesLike>,
      age: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [PythStructs.PriceStructOutput] & { price: PythStructs.PriceStructOutput }
    >;

    getEmaPriceUnsafe(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [PythStructs.PriceStructOutput] & { price: PythStructs.PriceStructOutput }
    >;

    getPriceNoOlderThan(
      id: PromiseOrValue<BytesLike>,
      age: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [PythStructs.PriceStructOutput] & { price: PythStructs.PriceStructOutput }
    >;

    getPriceUnsafe(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [PythStructs.PriceStructOutput] & { price: PythStructs.PriceStructOutput }
    >;

    getTwapUpdateFee(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { feeAmount: BigNumber }>;

    getUpdateFee(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { feeAmount: BigNumber }>;

    parsePriceFeedUpdates(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minPublishTime: PromiseOrValue<BigNumberish>,
      maxPublishTime: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    parsePriceFeedUpdatesUnique(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minPublishTime: PromiseOrValue<BigNumberish>,
      maxPublishTime: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    parsePriceFeedUpdatesWithConfig(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minAllowedPublishTime: PromiseOrValue<BigNumberish>,
      maxAllowedPublishTime: PromiseOrValue<BigNumberish>,
      checkUniqueness: PromiseOrValue<boolean>,
      checkUpdateDataIsMinimal: PromiseOrValue<boolean>,
      storeUpdatesIfFresh: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    parseTwapPriceFeedUpdates(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updatePriceFeeds(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updatePriceFeedsIfNecessary(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      publishTimes: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getEmaPriceNoOlderThan(
    id: PromiseOrValue<BytesLike>,
    age: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<PythStructs.PriceStructOutput>;

  getEmaPriceUnsafe(
    id: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<PythStructs.PriceStructOutput>;

  getPriceNoOlderThan(
    id: PromiseOrValue<BytesLike>,
    age: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<PythStructs.PriceStructOutput>;

  getPriceUnsafe(
    id: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<PythStructs.PriceStructOutput>;

  getTwapUpdateFee(
    updateData: PromiseOrValue<BytesLike>[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUpdateFee(
    updateData: PromiseOrValue<BytesLike>[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  parsePriceFeedUpdates(
    updateData: PromiseOrValue<BytesLike>[],
    priceIds: PromiseOrValue<BytesLike>[],
    minPublishTime: PromiseOrValue<BigNumberish>,
    maxPublishTime: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  parsePriceFeedUpdatesUnique(
    updateData: PromiseOrValue<BytesLike>[],
    priceIds: PromiseOrValue<BytesLike>[],
    minPublishTime: PromiseOrValue<BigNumberish>,
    maxPublishTime: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  parsePriceFeedUpdatesWithConfig(
    updateData: PromiseOrValue<BytesLike>[],
    priceIds: PromiseOrValue<BytesLike>[],
    minAllowedPublishTime: PromiseOrValue<BigNumberish>,
    maxAllowedPublishTime: PromiseOrValue<BigNumberish>,
    checkUniqueness: PromiseOrValue<boolean>,
    checkUpdateDataIsMinimal: PromiseOrValue<boolean>,
    storeUpdatesIfFresh: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  parseTwapPriceFeedUpdates(
    updateData: PromiseOrValue<BytesLike>[],
    priceIds: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updatePriceFeeds(
    updateData: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updatePriceFeedsIfNecessary(
    updateData: PromiseOrValue<BytesLike>[],
    priceIds: PromiseOrValue<BytesLike>[],
    publishTimes: PromiseOrValue<BigNumberish>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getEmaPriceNoOlderThan(
      id: PromiseOrValue<BytesLike>,
      age: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PythStructs.PriceStructOutput>;

    getEmaPriceUnsafe(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PythStructs.PriceStructOutput>;

    getPriceNoOlderThan(
      id: PromiseOrValue<BytesLike>,
      age: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PythStructs.PriceStructOutput>;

    getPriceUnsafe(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PythStructs.PriceStructOutput>;

    getTwapUpdateFee(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUpdateFee(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parsePriceFeedUpdates(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minPublishTime: PromiseOrValue<BigNumberish>,
      maxPublishTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PythStructs.PriceFeedStructOutput[]>;

    parsePriceFeedUpdatesUnique(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minPublishTime: PromiseOrValue<BigNumberish>,
      maxPublishTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PythStructs.PriceFeedStructOutput[]>;

    parsePriceFeedUpdatesWithConfig(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minAllowedPublishTime: PromiseOrValue<BigNumberish>,
      maxAllowedPublishTime: PromiseOrValue<BigNumberish>,
      checkUniqueness: PromiseOrValue<boolean>,
      checkUpdateDataIsMinimal: PromiseOrValue<boolean>,
      storeUpdatesIfFresh: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [PythStructs.PriceFeedStructOutput[], BigNumber[]] & {
        priceFeeds: PythStructs.PriceFeedStructOutput[];
        slots: BigNumber[];
      }
    >;

    parseTwapPriceFeedUpdates(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PythStructs.TwapPriceFeedStructOutput[]>;

    updatePriceFeeds(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    updatePriceFeedsIfNecessary(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      publishTimes: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "PriceFeedUpdate(bytes32,uint64,int64,uint64)"(
      id?: PromiseOrValue<BytesLike> | null,
      publishTime?: null,
      price?: null,
      conf?: null
    ): PriceFeedUpdateEventFilter;
    PriceFeedUpdate(
      id?: PromiseOrValue<BytesLike> | null,
      publishTime?: null,
      price?: null,
      conf?: null
    ): PriceFeedUpdateEventFilter;

    "TwapPriceFeedUpdate(bytes32,uint64,uint64,int64,uint64,uint32)"(
      id?: PromiseOrValue<BytesLike> | null,
      startTime?: null,
      endTime?: null,
      twapPrice?: null,
      twapConf?: null,
      downSlotsRatio?: null
    ): TwapPriceFeedUpdateEventFilter;
    TwapPriceFeedUpdate(
      id?: PromiseOrValue<BytesLike> | null,
      startTime?: null,
      endTime?: null,
      twapPrice?: null,
      twapConf?: null,
      downSlotsRatio?: null
    ): TwapPriceFeedUpdateEventFilter;
  };

  estimateGas: {
    getEmaPriceNoOlderThan(
      id: PromiseOrValue<BytesLike>,
      age: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEmaPriceUnsafe(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceNoOlderThan(
      id: PromiseOrValue<BytesLike>,
      age: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceUnsafe(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTwapUpdateFee(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUpdateFee(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parsePriceFeedUpdates(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minPublishTime: PromiseOrValue<BigNumberish>,
      maxPublishTime: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    parsePriceFeedUpdatesUnique(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minPublishTime: PromiseOrValue<BigNumberish>,
      maxPublishTime: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    parsePriceFeedUpdatesWithConfig(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minAllowedPublishTime: PromiseOrValue<BigNumberish>,
      maxAllowedPublishTime: PromiseOrValue<BigNumberish>,
      checkUniqueness: PromiseOrValue<boolean>,
      checkUpdateDataIsMinimal: PromiseOrValue<boolean>,
      storeUpdatesIfFresh: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    parseTwapPriceFeedUpdates(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updatePriceFeeds(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updatePriceFeedsIfNecessary(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      publishTimes: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getEmaPriceNoOlderThan(
      id: PromiseOrValue<BytesLike>,
      age: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEmaPriceUnsafe(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceNoOlderThan(
      id: PromiseOrValue<BytesLike>,
      age: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceUnsafe(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTwapUpdateFee(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUpdateFee(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parsePriceFeedUpdates(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minPublishTime: PromiseOrValue<BigNumberish>,
      maxPublishTime: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    parsePriceFeedUpdatesUnique(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minPublishTime: PromiseOrValue<BigNumberish>,
      maxPublishTime: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    parsePriceFeedUpdatesWithConfig(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      minAllowedPublishTime: PromiseOrValue<BigNumberish>,
      maxAllowedPublishTime: PromiseOrValue<BigNumberish>,
      checkUniqueness: PromiseOrValue<boolean>,
      checkUpdateDataIsMinimal: PromiseOrValue<boolean>,
      storeUpdatesIfFresh: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    parseTwapPriceFeedUpdates(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updatePriceFeeds(
      updateData: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updatePriceFeedsIfNecessary(
      updateData: PromiseOrValue<BytesLike>[],
      priceIds: PromiseOrValue<BytesLike>[],
      publishTimes: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
