/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, BytesLike, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IPythEventsInterface extends utils.Interface {
  functions: {};

  events: {
    "PriceFeedUpdate(bytes32,uint64,int64,uint64)": EventFragment;
    "TwapPriceFeedUpdate(bytes32,uint64,uint64,int64,uint64,uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PriceFeedUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TwapPriceFeedUpdate"): EventFragment;
}

export interface PriceFeedUpdateEventObject {
  id: string;
  publishTime: BigNumber;
  price: BigNumber;
  conf: BigNumber;
}
export type PriceFeedUpdateEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  PriceFeedUpdateEventObject
>;

export type PriceFeedUpdateEventFilter = TypedEventFilter<PriceFeedUpdateEvent>;

export interface TwapPriceFeedUpdateEventObject {
  id: string;
  startTime: BigNumber;
  endTime: BigNumber;
  twapPrice: BigNumber;
  twapConf: BigNumber;
  downSlotsRatio: number;
}
export type TwapPriceFeedUpdateEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, number],
  TwapPriceFeedUpdateEventObject
>;

export type TwapPriceFeedUpdateEventFilter =
  TypedEventFilter<TwapPriceFeedUpdateEvent>;

export interface IPythEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPythEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "PriceFeedUpdate(bytes32,uint64,int64,uint64)"(
      id?: PromiseOrValue<BytesLike> | null,
      publishTime?: null,
      price?: null,
      conf?: null
    ): PriceFeedUpdateEventFilter;
    PriceFeedUpdate(
      id?: PromiseOrValue<BytesLike> | null,
      publishTime?: null,
      price?: null,
      conf?: null
    ): PriceFeedUpdateEventFilter;

    "TwapPriceFeedUpdate(bytes32,uint64,uint64,int64,uint64,uint32)"(
      id?: PromiseOrValue<BytesLike> | null,
      startTime?: null,
      endTime?: null,
      twapPrice?: null,
      twapConf?: null,
      downSlotsRatio?: null
    ): TwapPriceFeedUpdateEventFilter;
    TwapPriceFeedUpdate(
      id?: PromiseOrValue<BytesLike> | null,
      startTime?: null,
      endTime?: null,
      twapPrice?: null,
      twapConf?: null,
      downSlotsRatio?: null
    ): TwapPriceFeedUpdateEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
